version: '3.8'

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend

  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app/
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/

  backend_v2:
    build: ./backend_v2
    env_file: ./backend_v2/.env
    ports:
      - '3000:3000'
    